# keystore(
#   name = 'debug',
#   store = 'debug.keystore',
#   properties = 'debug.keystore.properties',
#   visibility = [
#     'PUBLIC',
#   ],
# )
keystore(
  name = 'debug',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
  visibility = [
    'PUBLIC',
  ],
)
